name: Build Flutter Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get
                # Add step to check network connection before building
      - name: Check network connection to Gradle distributions
        run: curl -v https://services.gradle.org/distributions/gradle-8.7-bin.zip -o /dev/null

      # Build the Android release APK by directly calling Gradle Wrapper
      - name: Build APK
        working-directory: ./android # Change working directory to android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      # Upload the generated APK file as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # Path relative to the android directory, then up one level for workspace root
          path: android/app/build/outputs/apk/release/app-release.apk